#!/usr/bin/env bash
# Generates a local .env for development if one does not already exist.
# A real .env (e.g. provided via secrets) is never overwritten.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "[gen-env] .env already exists, leaving it untouched"
  exit 0
fi

echo "[gen-env] Writing development .env"
cat >"$ENV_FILE" <<'EOF'
# Local development environment (generated by .cursor/scripts/gen-env.sh)
# ── Backend ─────────────────────────────────────────────────────
APP_ID=dev-app
APP_SECRET=dev-secret-change-me

# ── Database ───────────────────────────────────────────────────
DATABASE_URL=mysql://root@127.0.0.1:3306/aquavolt

# ── Frontend (exposed to browser via Vite) ──────────────────────
VITE_KIMI_AUTH_URL=
VITE_APP_ID=dev-app

# ── Backend (Auth) ─────────────────────────────────────────────
# Kimi OAuth is optional in development; leave empty to run without login.
KIMI_AUTH_URL=
KIMI_OPEN_URL=

# ── Admin Role ──────────────────────────────────────────────────
OWNER_UNION_ID=
EOF
